const animalEmojis = {
  '🐵': 'Monkey Face',
  '🦍': 'Gorilla',
  '🦧': 'Orangutan',
  '🐶': 'Dog Face',
  '🐩': 'Poodle',
  '🐺': 'Wolf',
  '🦊': 'Fox',
  '🦝': 'Raccoon',
  '🐱': 'Cat Face',
  '🦁': 'Lion',
  '🐯': 'Tiger Face',
  '🐴': 'Horse Face',
  '🦄': 'Unicorn',
  '🦓': 'Zebra',
  '🦌': 'Deer',
  '🐮': 'Cow Face',
  '🐂': 'Ox',
  '🐃': 'Water Buffalo',
  '🐄': 'Cow',
  '🐷': 'Pig Face',
  '🐗': 'Boar',
  '🐏': 'Ram',
  '🐑': 'Ewe',
  '🐐': 'Goat',
  '🐪': 'Camel',
  '🦙': 'Llama',
  '🦒': 'Giraffe',
  '🐘': 'Elephant',
  '🦏': 'Rhinoceros',
  '🦛': 'Hippopotamus',
  '🐭': 'Mouse Face',
  '🐀': 'Rat',
  '🐹': 'Hamster',
  '🐰': 'Rabbit Face',
  '🐿️': 'Chipmunk',
  '🦔': 'Hedgehog',
  '🦇': 'Bat',
  '🐻': 'Bear',
  '🐨': 'Koala',
  '🐼': 'Panda',
  '🦥': 'Sloth',
  '🦦': 'Otter',
  '🦨': 'Skunk',
  '🦘': 'Kangaroo',
  '🦡': 'Badger',
  '🦃': 'Turkey',
  '🐔': 'Chicken',
  '🐓': 'Rooster',
  '🐤': 'Baby Chick',
  '🐦': 'Bird',
  '🐧': 'Penguin',
  '🕊️': 'Dove',
  '🦅': 'Eagle',
  '🦆': 'Duck',
  '🦢': 'Swan',
  '🦉': 'Owl',
  '🦩': 'Flamingo',
  '🦚': 'Peacock',
  '🦜': 'Parrot',
  '🐸': 'Frog',
  '🐊': 'Crocodile',
  '🐢': 'Turtle',
  '🦎': 'Lizard',
  '🐍': 'Snake',
  '🐲': 'Dragon Face',
  '🦕': 'Sauropod',
  '🦖': 'T-Rex',
  '🐳': 'Spouting Whale',
  '🐬': 'Dolphin',
  '🐟': 'Fish',
  '🐠': 'Tropical Fish',
  '🐡': 'Blowfish',
  '🦈': 'Shark',
  '🐙': 'Octopus',
  '🐌': 'Snail',
  '🦋': 'Butterfly',
  '🐛': 'Bug',
  '🐜': 'Ant',
  '🐝': 'Honeybee',
  '🐞': 'Lady Beetle',
  '🦗': 'Cricket',
  '🕷️': 'Spider',
  '🦂': 'Scorpion',
  '🦟': 'Mosquito',
  '🦠': 'Microbe',
  '🌲': 'Evergreen Tree',
  '🌳': 'Deciduous Tree',
  '🌴': 'Palm Tree',
  '🌵': 'Cactus',
  '🌾': 'Sheaf of Rice',
  '🌿': 'Herb',
  '🍀': 'Four Leaf Clover',
  '🍁': 'Maple Leaf',
  '🍄': 'Mushroom',
  '🌰': 'Chestnut',
  '🦀': 'Crab',
  '🦞': 'Lobster',
  '🦐': 'Shrimp',
  '🦑': 'Squid',
}

export default animalEmojis