interface Animojis {
  [key: string]: string
}
const animalEmojis: Animojis = {
  'Monkey': '🐵',
  'Gorilla': '🦍',
  'Orangutan': '🦧',
  'Dog': '🐶',
  'Poodle': '🐩',
  'Wolf': '🐺',
  'Fox': '🦊',
  'Raccoon': '🦝',
  'Cat': '🐱',
  'Lion': '🦁',
  'Tiger': '🐯',
  'Horse': '🐴',
  'Unicorn': '🦄',
  'Zebra': '🦓',
  'Deer': '🦌',
  'Dasher': '🦌',
  'Dancer': '🦌',
  'Prancer': '🦌',
  'Vixen': '🦌',
  'Comet': '🦌',
  'Cupid': '🦌',
  'Dunder': '🦌',
  'Blixen': '🦌',
  'Rudolph': '🦌',
  'Cow': '🐮',
  'Ox': '🐂',
  'Water Buffalo': '🐃',
  'Pig': '🐷',
  'Boar': '🐗',
  'Ram': '🐏',
  'Ewe': '🐑',
  'Goat': '🐐',
  'Camel': '🐪',
  'Llama': '🦙',
  'Giraffe': '🦒',
  'Elephant': '🐘',
  'Rhinoceros': '🦏',
  'Hippopotamus': '🦛',
  'Mouse': '🐭',
  'Rat': '🐀',
  'Hamster': '🐹',
  'Rabbit': '🐰',
  'Chipmunk': '🐿️',
  'Hedgehog': '🦔',
  'Bat': '🦇',
  'Bear': '🐻',
  'Koala': '🐨',
  'Panda': '🐼',
  'Sloth': '🦥',
  'Otter': '🦦',
  'Skunk': '🦨',
  'Kangaroo': '🦘',
  'Badger': '🦡',
  'Turkey': '🦃',
  'Chicken': '🐔',
  'Rooster': '🐓',
  'Baby Chick': '🐤',
  'Bird': '🐦',
  'Penguin': '🐧',
  'Dove': '🕊️',
  'Eagle': '🦅',
  'Duck': '🦆',
  'Swan': '🦢',
  'Owl': '🦉',
  'Flamingo': '🦩',
  'Peacock': '🦚',
  'Parrot': '🦜',
  'Frog': '🐸',
  'Crocodile': '🐊',
  'Turtle': '🐢',
  'Lizard': '🦎',
  'Snake': '🐍',
  'Dragon': '🐲',
  'Sauropod': '🦕',
  'T-Rex': '🦖',
  'Whale': '🐳',
  'Dolphin': '🐬',
  'Fish': '🐟',
  'Tropical Fish': '🐠',
  'Blowfish': '🐡',
  'Shark': '🦈',
  'Octopus': '🐙',
  'Snail': '🐌',
  'Butterfly': '🦋',
  'Bug': '🐛',
  'Ant': '🐜',
  'Honeybee': '🐝',
  'Lady Beetle': '🐞',
  'Cricket': '🦗',
  'Spider': '🕷️',
  'Scorpion': '🦂',
  'Mosquito': '🦟',
  'Microbe': '🦠',
  'Evergreen Tree': '🌲',
  'Deciduous Tree': '🌳',
  'Palm Tree': '🌴',
  'Cactus': '🌵',
  'Sheaf of Rice': '🌾',
  'Herb': '🌿',
  'Clover': '🍀',
  'Maple Leaf': '🍁',
  'Mushroom': '🍄',
  'Chestnut': '🌰',
  'Crab': '🦀',
  'Lobster': '🦞',
  'Shrimp': '🦐',
  'Squid': '🦑',
}

const getEmoji = (username: string) => {
  let emoji = animalEmojis[username]
  return emoji
}

export { animalEmojis, getEmoji }